// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cassini.proto

package cassini

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cassini_241e40df5787421e, []int{0}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (dst *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(dst, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingReply struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cassini_241e40df5787421e, []int{1}
}
func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (dst *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(dst, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

func (m *PingReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cassini_241e40df5787421e, []int{2}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cassini_241e40df5787421e, []int{3}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "cassini.PingRequest")
	proto.RegisterType((*PingReply)(nil), "cassini.PingReply")
	proto.RegisterType((*GetRequest)(nil), "cassini.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "cassini.GetResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CassiniControllerClient is the client API for CassiniController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CassiniControllerClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type cassiniControllerClient struct {
	cc *grpc.ClientConn
}

func NewCassiniControllerClient(cc *grpc.ClientConn) CassiniControllerClient {
	return &cassiniControllerClient{cc}
}

func (c *cassiniControllerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/cassini.CassiniController/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cassiniControllerClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/cassini.CassiniController/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CassiniControllerServer is the server API for CassiniController service.
type CassiniControllerServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

func RegisterCassiniControllerServer(s *grpc.Server, srv CassiniControllerServer) {
	s.RegisterService(&_CassiniController_serviceDesc, srv)
}

func _CassiniController_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CassiniControllerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cassini.CassiniController/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CassiniControllerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CassiniController_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CassiniControllerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cassini.CassiniController/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CassiniControllerServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CassiniController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cassini.CassiniController",
	HandlerType: (*CassiniControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _CassiniController_Ping_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CassiniController_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cassini.proto",
}

func init() { proto.RegisterFile("cassini.proto", fileDescriptor_cassini_241e40df5787421e) }

var fileDescriptor_cassini_241e40df5787421e = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x5d, 0x4a, 0x33, 0x31,
	0x14, 0x86, 0x99, 0xf6, 0xe3, 0xab, 0x3d, 0x65, 0xb0, 0x1e, 0x2b, 0x0c, 0x83, 0x88, 0x04, 0x04,
	0xaf, 0x1a, 0xaa, 0x3b, 0xb0, 0x17, 0x73, 0x2b, 0xdd, 0xc1, 0x28, 0x87, 0x21, 0x34, 0xe4, 0xc4,
	0x24, 0x53, 0x18, 0xc4, 0x1b, 0xb7, 0xe0, 0x06, 0xdc, 0x93, 0x5b, 0x70, 0x21, 0x92, 0xc9, 0xd4,
	0xdf, 0xbb, 0xbc, 0x6f, 0x9e, 0x73, 0x78, 0x12, 0xc8, 0xef, 0x6b, 0xef, 0x95, 0x51, 0x4b, 0xeb,
	0x38, 0x30, 0x4e, 0x86, 0x58, 0x9e, 0x36, 0xcc, 0x8d, 0x26, 0x59, 0x5b, 0x25, 0x6b, 0x63, 0x38,
	0xd4, 0x41, 0xb1, 0xf1, 0x09, 0x13, 0x39, 0xcc, 0x6e, 0x95, 0x69, 0x36, 0xf4, 0xd0, 0x92, 0x0f,
	0xe2, 0x02, 0xa6, 0x29, 0x5a, 0xdd, 0x61, 0x01, 0x93, 0x1d, 0x39, 0xaf, 0xd8, 0x14, 0xd9, 0x79,
	0x76, 0x39, 0xdd, 0xec, 0xa3, 0x38, 0x03, 0xa8, 0x28, 0x0c, 0x43, 0x38, 0x87, 0xf1, 0x96, 0xba,
	0x81, 0x89, 0x47, 0xb1, 0x82, 0x59, 0x7f, 0xef, 0x2d, 0x1b, 0x4f, 0x7f, 0x81, 0xd8, 0xb4, 0x4e,
	0x17, 0xa3, 0xd4, 0xb4, 0x4e, 0x5f, 0xbd, 0x66, 0x70, 0xb4, 0x4e, 0xca, 0x6b, 0x36, 0xc1, 0xb1,
	0xd6, 0xe4, 0xf0, 0x06, 0xfe, 0x45, 0x1f, 0x5c, 0x2c, 0xf7, 0xaf, 0xfb, 0x66, 0x5b, 0xe2, 0xaf,
	0xd6, 0xea, 0x4e, 0xcc, 0x9f, 0xdf, 0xde, 0x5f, 0x46, 0x80, 0x07, 0x72, 0xb7, 0x92, 0x36, 0xce,
	0x56, 0x30, 0xae, 0x28, 0xe0, 0xf1, 0x27, 0xfc, 0xa5, 0x5e, 0x2e, 0x7e, 0x96, 0xc9, 0x57, 0x9c,
	0xf4, 0x3b, 0x0e, 0x31, 0x8f, 0x3b, 0x1a, 0x0a, 0xf2, 0x71, 0x4b, 0xdd, 0xd3, 0xdd, 0xff, 0xfe,
	0xcb, 0xae, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x31, 0x9e, 0x8a, 0xc2, 0x6a, 0x01, 0x00, 0x00,
}
