// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cassini.proto

package cassini

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CacheLocation struct {
	Dc                   string   `protobuf:"bytes,1,opt,name=dc,proto3" json:"dc,omitempty"`
	Rack                 string   `protobuf:"bytes,2,opt,name=rack,proto3" json:"rack,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheLocation) Reset()         { *m = CacheLocation{} }
func (m *CacheLocation) String() string { return proto.CompactTextString(m) }
func (*CacheLocation) ProtoMessage()    {}
func (*CacheLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_cassini_a523d572c3e12b8d, []int{0}
}
func (m *CacheLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheLocation.Unmarshal(m, b)
}
func (m *CacheLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheLocation.Marshal(b, m, deterministic)
}
func (dst *CacheLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheLocation.Merge(dst, src)
}
func (m *CacheLocation) XXX_Size() int {
	return xxx_messageInfo_CacheLocation.Size(m)
}
func (m *CacheLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheLocation.DiscardUnknown(m)
}

var xxx_messageInfo_CacheLocation proto.InternalMessageInfo

func (m *CacheLocation) GetDc() string {
	if m != nil {
		return m.Dc
	}
	return ""
}

func (m *CacheLocation) GetRack() string {
	if m != nil {
		return m.Rack
	}
	return ""
}

func (m *CacheLocation) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Object struct {
	Key                  string           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Origin               string           `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Locations            []*CacheLocation `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_cassini_a523d572c3e12b8d, []int{1}
}
func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (dst *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(dst, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Object) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Object) GetLocations() []*CacheLocation {
	if m != nil {
		return m.Locations
	}
	return nil
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cassini_a523d572c3e12b8d, []int{2}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (dst *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(dst, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingReply struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cassini_a523d572c3e12b8d, []int{3}
}
func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (dst *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(dst, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

func (m *PingReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cassini_a523d572c3e12b8d, []int{4}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetReply struct {
	Object               *Object  `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReply) Reset()         { *m = GetReply{} }
func (m *GetReply) String() string { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()    {}
func (*GetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cassini_a523d572c3e12b8d, []int{5}
}
func (m *GetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReply.Unmarshal(m, b)
}
func (m *GetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReply.Marshal(b, m, deterministic)
}
func (dst *GetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReply.Merge(dst, src)
}
func (m *GetReply) XXX_Size() int {
	return xxx_messageInfo_GetReply.Size(m)
}
func (m *GetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetReply proto.InternalMessageInfo

func (m *GetReply) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

func init() {
	proto.RegisterType((*CacheLocation)(nil), "cassini.CacheLocation")
	proto.RegisterType((*Object)(nil), "cassini.Object")
	proto.RegisterType((*PingRequest)(nil), "cassini.PingRequest")
	proto.RegisterType((*PingReply)(nil), "cassini.PingReply")
	proto.RegisterType((*GetRequest)(nil), "cassini.GetRequest")
	proto.RegisterType((*GetReply)(nil), "cassini.GetReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CassiniClient is the client API for Cassini service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CassiniClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
}

type cassiniClient struct {
	cc *grpc.ClientConn
}

func NewCassiniClient(cc *grpc.ClientConn) CassiniClient {
	return &cassiniClient{cc}
}

func (c *cassiniClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/cassini.Cassini/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cassiniClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, "/cassini.Cassini/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CassiniServer is the server API for Cassini service.
type CassiniServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	Get(context.Context, *GetRequest) (*GetReply, error)
}

func RegisterCassiniServer(s *grpc.Server, srv CassiniServer) {
	s.RegisterService(&_Cassini_serviceDesc, srv)
}

func _Cassini_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CassiniServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cassini.Cassini/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CassiniServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cassini_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CassiniServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cassini.Cassini/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CassiniServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cassini_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cassini.Cassini",
	HandlerType: (*CassiniServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Cassini_Ping_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Cassini_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cassini.proto",
}

func init() { proto.RegisterFile("cassini.proto", fileDescriptor_cassini_a523d572c3e12b8d) }

var fileDescriptor_cassini_a523d572c3e12b8d = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xdd, 0x4e, 0xc2, 0x30,
	0x14, 0x0e, 0x1b, 0x19, 0x70, 0xc8, 0x04, 0x8f, 0x4a, 0x16, 0x62, 0x0c, 0x69, 0x62, 0xe4, 0x8a,
	0x45, 0xf0, 0x09, 0x44, 0xc3, 0x8d, 0x89, 0x66, 0x6f, 0x30, 0x4a, 0x33, 0x2a, 0x4b, 0x3b, 0xb7,
	0x42, 0xb2, 0x18, 0x6f, 0x7c, 0x05, 0x1e, 0xcd, 0x57, 0xf0, 0x41, 0x4c, 0xbb, 0x02, 0xa2, 0x77,
	0xe7, 0xfb, 0xe9, 0x77, 0xbe, 0x93, 0x82, 0x4f, 0xe3, 0xa2, 0xe0, 0x82, 0x8f, 0xb2, 0x5c, 0x2a,
	0x89, 0x0d, 0x0b, 0xfb, 0x97, 0x89, 0x94, 0x49, 0xca, 0xc2, 0x38, 0xe3, 0x61, 0x2c, 0x84, 0x54,
	0xb1, 0xe2, 0x52, 0x14, 0x95, 0x8d, 0x3c, 0x82, 0x3f, 0x8d, 0xe9, 0x92, 0x3d, 0x49, 0x6a, 0x78,
	0x3c, 0x01, 0x67, 0x41, 0x83, 0xda, 0xa0, 0x36, 0x6c, 0x45, 0xce, 0x82, 0x22, 0x42, 0x3d, 0x8f,
	0xe9, 0x2a, 0x70, 0x0c, 0x63, 0x66, 0xec, 0x82, 0xbb, 0xce, 0xd3, 0xc0, 0x35, 0x94, 0x1e, 0xc9,
	0x12, 0xbc, 0xe7, 0xf9, 0x2b, 0xa3, 0x4a, 0x6b, 0x2b, 0x56, 0xda, 0x00, 0x3d, 0x62, 0x0f, 0x3c,
	0x99, 0xf3, 0x84, 0x0b, 0x9b, 0x61, 0x11, 0xde, 0x41, 0x2b, 0xb5, 0x5b, 0x8b, 0xc0, 0x1d, 0xb8,
	0xc3, 0xf6, 0xb8, 0x37, 0xda, 0x1d, 0x71, 0x54, 0x2a, 0x3a, 0x18, 0x89, 0x0f, 0xed, 0x17, 0x2e,
	0x92, 0x88, 0xbd, 0xad, 0x59, 0xa1, 0xc8, 0x35, 0xb4, 0x2a, 0x98, 0xa5, 0x25, 0x06, 0xd0, 0xd8,
	0xb0, 0xbc, 0xe0, 0x52, 0xd8, 0xfd, 0x3b, 0x48, 0xae, 0x00, 0x66, 0x4c, 0xd9, 0x47, 0xff, 0x3b,
	0x92, 0x09, 0x34, 0x8d, 0xae, 0x53, 0x6e, 0xc0, 0x93, 0xe6, 0x16, 0x63, 0x68, 0x8f, 0x3b, 0xfb,
	0x52, 0xd5, 0x89, 0x91, 0x95, 0xc7, 0xdb, 0x1a, 0x34, 0xa6, 0x95, 0x84, 0xf7, 0x50, 0xd7, 0x3d,
	0xf0, 0x7c, 0x6f, 0xfe, 0xd5, 0xb2, 0x8f, 0x7f, 0xd8, 0x2c, 0x2d, 0x49, 0xf7, 0xf3, 0xeb, 0x7b,
	0xeb, 0x00, 0x36, 0xc3, 0xcd, 0x6d, 0x98, 0xe9, 0xb7, 0x0f, 0xe0, 0xce, 0x98, 0xc2, 0xb3, 0xbd,
	0xf9, 0x50, 0xb9, 0x7f, 0x7a, 0x4c, 0xea, 0x80, 0x0b, 0x13, 0xd0, 0x41, 0x5f, 0x07, 0x24, 0x4c,
	0x85, 0xef, 0x2b, 0x56, 0x7e, 0xcc, 0x3d, 0xf3, 0xb1, 0x93, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x76, 0xa1, 0x44, 0x9c, 0x10, 0x02, 0x00, 0x00,
}
